version: "3"
services:
  app:
    image: myapp
    restart: on-failure
    build: .
    depends_on:
      - postgres
    environment:
      APP_PORT: 80
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: db
      DB_HOST: postgres
    ports:
      - "3000:3000"
      - "80:80"
    command: npm run start
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:11
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

  migration:
    image: myapp
    command:
      - /bin/bash
      - -c
      - |
        ./wait-for-it/wait-for-it.sh postgres:5432 -- npm run migrate && npm run filldb
    environment:
      APP_URL: ${APP_URL}
      APP_PORT: 80
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: db
    links:
      - postgres
    depends_on:
      - postgres
