'use strict';

const MAX_COMMENT_LENGTH = 100;
const MAX_POPULAR_ARTICLES = 4;
const MAX_LATEST_ARTICLES = 4;

module.exports = {
  MAX_COMMENT_LENGTH,
  MAX_POPULAR_ARTICLES,
  MAX_LATEST_ARTICLES
};
